name: AutoBuild

on: 
  push:
    tags:
    - '*'
  release:
    types:
      - created

env:
  DOTNET_SDK_VERSION: 6.0.x

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.5
        with:
          submodules: recursive

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1.8.2
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}

      - name: Verify .NET Core
        run: dotnet --info

      - name: Restore packages in preparation for ASFEnhance publishing
        run: dotnet restore ASFEnhance -p:ContinuousIntegrationBuild=true --nologo

      - name: Publish ASFEnhance on Windows
        shell: pwsh
        run: |
          $script = "./build.ps1";
          Set-Location ${{ github.workspace }};
          powershell $script;

      - name: Upload ASFEnhance-zh-CN
        continue-on-error: true
        uses: actions/upload-artifact@v2.2.4
        with:
          name: ASFEnhance-zh-CN
          path: dist/ASFEnhance-zh-CN.zip

      - name: Upload ASFEnhance-en-US
        continue-on-error: true
        uses: actions/upload-artifact@v2.2.4
        with:
          name: ASFEnhance-en-US
          path: dist/ASFEnhance-en-US.zip

  release:
    needs: publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.5

      - name: Download ASFEnhance-zh-CN artifact from windows-latest
        uses: actions/download-artifact@v2.0.10
        with:
          name: ASFEnhance-zh-CN
          path: out

      - name: Download ASFEnhance-en-US artifact from windows-latest
        uses: actions/download-artifact@v2.0.10
        with:
          name: ASFEnhance-en-US
          path: out

      - name: Create ASFEnhance GitHub release
        id: github_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ASFEnhance ${{ github.ref }}
          body: release created bt github actions
          prerelease: false

      - name: Upload ASFEnhance-zh-CN to GitHub release
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.github_release.outputs.upload_url }}
          asset_path: out/ASFEnhance-zh-CN.zip
          asset_name: ASFEnhance-zh-CN.zip
          asset_content_type: application/zip
     
      - name: Upload ASFEnhance-zh-CN to GitHub release
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.github_release.outputs.upload_url }}
          asset_path: out/ASFEnhance-en-US.zip
          asset_name: ASFEnhance-en-US.zip
          asset_content_type: application/zip
